export { default as IntroSection } from './intro'
export { default as PassionSectionTitle } from './passion.title'
export { default as PassionSectionContent } from './passion.content'
export { default as MarqueeSection } from './marquee'
export { default as SkillsSection } from './skills'
